<?php

namespace AppBundle\Repository;

use DateTime;
use Doctrine\ORM\Query;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $limit
     * @return mixed
     */
    public function findLatest(int $limit = 10) {
        return $this->createQueryBuilder('m')
            ->orderBy('m.createdAt', 'ASC')
            ->getQuery()
            ->execute();
    }

    /**
     * @param array $years
     * @param int|null $currentPage
     * @param int|null $limit
     * @return Paginator
     */
    public function findManyByYears(array $years, int $currentPage = 1, int $limit = 20) {
        $qb = $this->createQueryBuilder('m');

        foreach ($years as $index => $year) {
            $statement = 'm.releaseDate BETWEEN :from' . $index . ' AND :to' . $index;

            $from = DateTime::createFromFormat('Y-m-d', $year . '-01-01');
            $to = DateTime::createFromFormat('Y-m-d', (int)$year + 1 . '-01-01');

            if ($index == 0) {
                $qb->where($statement);
            } else {
                $qb->orWhere($statement);
            }

            $qb->setParameter('from' . $index, $from->format('Y-m-d'));
            $qb->setParameter('to' . $index, $to->format('Y-m-d'));
        }

        return $this->paginate($qb->getQuery(), $currentPage, $limit);
    }

    /**
     * @param Query $query
     * @param int $page
     * @param int $limit
     * @return Paginator
     */
    private function paginate(Query $query, int $page, int $limit): Paginator {
        $paginator = new Paginator($query);
        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1))
            ->setMaxResults($limit);

        return $paginator;
    }
}