<?php

namespace AppBundle\Repository;

/**
 * QualityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualityRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $movieId
     * @return mixed
     */
    public function findManyByMovieId(int $movieId) {
        return $this->createQueryBuilder('q')
            ->innerJoin('q.torrents', 't')
            ->innerJoin('t.movie', 'm')
            ->where('m.id = :movieId')
            ->setParameter('movieId', $movieId)
            ->getQuery()->execute();
    }
}
