<?php

namespace AppBundle\Repository;

/**
 * QualityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualityRepository extends \Doctrine\ORM\EntityRepository
{
}
