<?php

namespace AppBundle\Repository;

/**
 * TorrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TorrentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $movie_id
     * @param int $format
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByMovieIdAndFormat(int $movie_id, int $format) {
        return $this->createQueryBuilder('t')
            ->innerJoin('t.movie', 'm')
            ->innerJoin('t.quality', 'q')
            ->andWhere('m.id = :movie_id AND q.format = :format')
            ->setParameter('movie_id', $movie_id)
            ->setParameter('format', $format)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
